### ISSUE TITLE
Get inscription by inscription id

### ISSUE THREAD

**Issue by andredevjs** [dannydeezy/nosft#106]
We need to get as much information as the current getUtxo's function instead of using the address as a parameter, it should be the inscription id.

We will use this to feed the details page, in which, we should be able to view and send the inscription.

**Comment by habibitcoin** [comment]
I don't think it will make much sense to get this and https://github.com/dannydeezy/nosft/issues/105 separately

Looked at the available options pretty thoroughly when evaluating the infinity scroll implementation; the problem is that in order get all your utxos, you have to:
1. make at least 1 call to blockstream/mempool. 
2. Make a call to https://turbo.ordinalswallet.com/wallet/bc1pp0rw32sewn2m8x75squkkkpy3nwxc8cs7kaxx0k4gk3rc0977c2qtq2t2d/inscriptions to get all my inscriptions; keep in mind though I have no idea which inscriptions belong to me at this point
3. In order to map utxos + inscriptions, I have to call /outpoint now for all of my utxos, which we then make sure to store into localstorage

**Comment by habibitcoin** [comment]
Or I suppose this method would be dependcy for unauthenticated users is the idea? On homepage?

**Comment by andredevjs** [comment]
Done in https://github.com/dannydeezy/nosft/pull/102
