### ISSUE TITLE
Add some type of caching for the initial UTXO load

### ISSUE THREAD

**Issue by dannydeezy** [dannydeezy/nosft#66]
Currently we are doing a lot of heavy calls to get the address's historical transactions, then calculating existing utxos. its super slow

**Comment by Uthpala** [comment]
My proposal to this issue is to only fetch the initial utxos and only fetch the next set of utxos if the client request for it. 

To do this - 
I will remove the while loop in - https://github.com/dannydeezy/nosft/blob/main/src/utils/utxos.js#L17

Next make the api so that the client pass in the lastTxId to get the next set of utxos. 

This will make the initial page loads faster and the reduce use of unnecessary use of API.

**Comment by habibitcoin** [comment]
Cached in local storage now
